on: [push, pull_request]
name: Continuous Integration

# Inspired by osu! lazer's CI
# https://github.com/ppy/osu/blob/e12249f1270a22cf5811a8bb7a9ee44f2c0250db/.github/workflows/ci.yml

jobs:
  test:
    name: Build & Test
    runs-on: ${{matrix.os.fullName}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { prettyName: Windows, fullName: windows-latest }
          - { prettyName: macOS, fullName: macos-latest }
          - { prettyName: Linux, fullName: ubuntu-latest }

    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
          include-prerelease: true

      - name: Install .NET 6.0 Preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true
          
      - name: Compile
        run: dotnet build -c Debug
        
      - name: Make sure the default MySQL service is stopped
        run: sudo service mysql stop

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'lighthouse'
          mysql user: 'lighthouse'
          mysql password: 'lighthouse'
          
      - name: Run database migrations
        run: mysql -u lighthouse -p lighthouse lighthouse < DatabaseMigrations/*.sql
        
      - name: Test
        continue-on-error: true
        run: dotnet test --logger "trx;LogFileName=${{github.workspace}}/TestResults-${{matrix.os.prettyName}}.trx"


      # Attempt to upload results even if test fails.
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#always
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: lighthouse-test-results-${{matrix.os.prettyName}}
          path: ${{github.workspace}}/TestResults-${{matrix.os.prettyName}}.trx

      - name: Process Test Results
        if: ${{ always() }}
        uses: im-open/process-dotnet-test-results@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Test Results
        if: steps.process-trx.outputs.test-outcome == 'Failed'
        run: |
          echo "There were test failures."
          exit 1