# Yoinked from https://github.com/ppy/osu/blob/e12249f1270a22cf5811a8bb7a9ee44f2c0250db/.github/workflows/report-nunit.yml
# This is a workaround to allow PRs to report their coverage. This will run inside the base repository.
# See:
#   * https://github.com/dorny/test-reporter#recommended-setup-for-public-repositories
#   * https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
name: Annotate CI run with test results
on:
  workflow_run:
    workflows: [ "Continuous Integration" ]
    types:
      - completed
jobs:
  annotate:
    name: Annotate CI run with test results
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { prettyname: Windows }
          - { prettyname: macOS }
          - { prettyname: Linux }
    timeout-minutes: 5
    steps:
      - name: Annotate CI run with test results
        uses: dorny/test-reporter@v1.4.2
        with:
          artifact: lighthouse-test-results-${{matrix.os.prettyName}}
          name: Test Results (${{matrix.os.prettyname}})
          path: "*.trx"
          reporter: dotnet-trx